name: Java CI with Maven

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - [cite_start]uses: actions/checkout@v3 [cite: 109]
    - name: Set up JDK 23
      [cite_start]uses: actions/setup-java@v3 [cite: 331]
      with:
        java-version: '23'
        distribution: 'temurin'
        cache: 'maven'
    - name: Build with Maven
      [cite_start]run: mvn -B package -DskipTests --file pom.xml [cite: 343, 431]